#!/bin/sh
# chkconfig: 2345 90 10
# description: Zookeeper server

ZK_DIR=/server/zk/zk_2181
EXEC=$ZK_DIR/bin/zkServer.sh

export JAVA_HOME=/usr/local/jdk1.8.0_162
export PATH=$JAVA_HOME/bin:$PATH

PID=$(ps -ef |grep $ZK_DIR |grep -v grep |awk '{print $2}')
# ps -ef |grep /server/zk/zk_2181 |grep -v grep |awk '{print $2}'

case "$1" in
    start)
      if [ -z "$PID" ]
      then
          echo "Starting Zookeeper..."
          $EXEC start
      else
          echo "$PID exists, process is already running or crashed"
      fi
    ;;
    stop)
	echo '====$PID'
      if [ -n "$PID" ]
      then
          echo "Stop Zookeeper..."
          $EXEC stop
      fi
      echo "Zookeeper stopped"
    ;;
esac